# Generated by Django 5.2.16 on 2026-09-28 04:09

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpage',
            name='video_banner_image',
            field=core.fields.WebPImageField(blank=True, upload_to='careers/banner/'),
        ),
    ]
