# Generated by Django 5.2.16 on 2026-09-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_careerpage_video_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpage',
            name='video_banner_image',
            field=models.ImageField(blank=True, upload_to='careers/banner/'),
        ),
    ]
