# Generated by Django 5.2.16 on 2026-09-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_careerpage_video_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='careerpage',
            name='hero_description',
            field=models.TextField(blank=True, default="We're more than a construction company — we're a team of builders, thinkers and problem-solvers shaping skylines and communities. If you're passionate about craftsmanship and growth, there's a place for you here."),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='hero_description_ar',
            field=models.TextField(blank=True, default="We're more than a construction company — we're a team of builders, thinkers and problem-solvers shaping skylines and communities. If you're passionate about craftsmanship and growth, there's a place for you here.", null=True),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='hero_description_en',
            field=models.TextField(blank=True, default="We're more than a construction company — we're a team of builders, thinkers and problem-solvers shaping skylines and communities. If you're passionate about craftsmanship and growth, there's a place for you here.", null=True),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='hero_description_fr',
            field=models.TextField(blank=True, default="We're more than a construction company — we're a team of builders, thinkers and problem-solvers shaping skylines and communities. If you're passionate about craftsmanship and growth, there's a place for you here.", null=True),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='careers/hero/'),
        ),
    ]
