# Generated by Django 5.2.16 on 2026-09-28 04:09

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=core.fields.WebPImageField(blank=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_1',
            field=core.fields.WebPImageField(blank=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_2',
            field=core.fields.WebPImageField(blank=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='testimonial_avatar',
            field=core.fields.WebPImageField(blank=True, upload_to='projects/testimonials/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_cover',
            field=core.fields.WebPImageField(blank=True, upload_to='projects/video/'),
        ),
    ]
