# Generated by Django 5.2.16 on 2026-09-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image_alter_project_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='testimonial_avatar',
            field=models.ImageField(blank=True, upload_to='projects/testimonials/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_cover',
            field=models.ImageField(blank=True, upload_to='projects/video/'),
        ),
    ]
