# Generated by Django 5.2.16 on 2026-09-28 04:09

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=core.fields.WebPImageField(blank=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_avatar',
            field=core.fields.WebPImageField(blank=True, upload_to='testimonials/'),
        ),
    ]
