# Generated by Django 5.2.16 on 2026-09-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammember_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_avatar',
            field=models.ImageField(blank=True, upload_to='testimonials/'),
        ),
    ]
