# Generated by Django 5.2.16 on 2026-09-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
