# Generated by Django 5.2.16 on 2026-09-28 04:09

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=core.fields.WebPImageField(blank=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_1',
            field=core.fields.WebPImageField(blank=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_2',
            field=core.fields.WebPImageField(blank=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='video_cover',
            field=core.fields.WebPImageField(blank=True, upload_to='services/video/'),
        ),
    ]
