# Generated by Django 5.2.16 on 2026-09-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_image_alter_service_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='includes_title',
            field=models.CharField(default="What's Included", max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='includes_title_ar',
            field=models.CharField(default="What's Included", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='includes_title_en',
            field=models.CharField(default="What's Included", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='includes_title_fr',
            field=models.CharField(default="What's Included", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='video_cover',
            field=models.ImageField(blank=True, upload_to='services/video/'),
        ),
    ]
