# Generated by Django 5.2.16 on 2026-09-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Override the default title tag (max 60 chars).', max_length=60)),
                ('meta_title_fr', models.CharField(blank=True, help_text='Override the default title tag (max 60 chars).', max_length=60, null=True)),
                ('meta_title_en', models.CharField(blank=True, help_text='Override the default title tag (max 60 chars).', max_length=60, null=True)),
                ('meta_title_ar', models.CharField(blank=True, help_text='Override the default title tag (max 60 chars).', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description (max 160 chars).', max_length=160)),
                ('meta_description_fr', models.TextField(blank=True, help_text='Meta description (max 160 chars).', max_length=160, null=True)),
                ('meta_description_en', models.TextField(blank=True, help_text='Meta description (max 160 chars).', max_length=160, null=True)),
                ('meta_description_ar', models.TextField(blank=True, help_text='Meta description (max 160 chars).', max_length=160, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255)),
                ('meta_keywords_fr', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255, null=True)),
                ('meta_keywords_en', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255, null=True)),
                ('meta_keywords_ar', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, max_length=60)),
                ('og_title_fr', models.CharField(blank=True, max_length=60, null=True)),
                ('og_title_en', models.CharField(blank=True, max_length=60, null=True)),
                ('og_title_ar', models.CharField(blank=True, max_length=60, null=True)),
                ('og_description', models.TextField(blank=True, max_length=160)),
                ('og_description_fr', models.TextField(blank=True, max_length=160, null=True)),
                ('og_description_en', models.TextField(blank=True, max_length=160, null=True)),
                ('og_description_ar', models.TextField(blank=True, max_length=160, null=True)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('twitter_card', models.CharField(blank=True, choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', max_length=20)),
                ('canonical_url', models.URLField(blank=True)),
                ('noindex', models.BooleanField(default=False)),
                ('nofollow', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=300)),
                ('title_fr', models.CharField(max_length=300, null=True)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('title_ar', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('category_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('category_en', models.CharField(blank=True, max_length=100, null=True)),
                ('category_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('author_name', models.CharField(default='BS GROUP', max_length=200)),
                ('author_name_fr', models.CharField(default='BS GROUP', max_length=200, null=True)),
                ('author_name_en', models.CharField(default='BS GROUP', max_length=200, null=True)),
                ('author_name_ar', models.CharField(default='BS GROUP', max_length=200, null=True)),
                ('author_avatar', models.ImageField(blank=True, upload_to='blog/avatars/')),
                ('author_bio', models.TextField(blank=True)),
                ('author_bio_fr', models.TextField(blank=True, null=True)),
                ('author_bio_en', models.TextField(blank=True, null=True)),
                ('author_bio_ar', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('excerpt', models.TextField(blank=True)),
                ('excerpt_fr', models.TextField(blank=True, null=True)),
                ('excerpt_en', models.TextField(blank=True, null=True)),
                ('excerpt_ar', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, help_text='Contenu HTML de l’article')),
                ('content_fr', models.TextField(blank=True, help_text='Contenu HTML de l’article', null=True)),
                ('content_en', models.TextField(blank=True, help_text='Contenu HTML de l’article', null=True)),
                ('content_ar', models.TextField(blank=True, help_text='Contenu HTML de l’article', null=True)),
                ('reading_time', models.CharField(default='5 min Read', max_length=50)),
                ('reading_time_fr', models.CharField(default='5 min Read', max_length=50, null=True)),
                ('reading_time_en', models.CharField(default='5 min Read', max_length=50, null=True)),
                ('reading_time_ar', models.CharField(default='5 min Read', max_length=50, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('tags_fr', models.CharField(blank=True, max_length=500, null=True)),
                ('tags_en', models.CharField(blank=True, max_length=500, null=True)),
                ('tags_ar', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-published'],
            },
        ),
    ]
