# Generated by Django 5.2.16 on 2026-09-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author_avatar_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_avatar',
            field=models.ImageField(blank=True, upload_to='blog/avatars/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text="Contenu HTML de l'article"),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_ar',
            field=models.TextField(blank=True, help_text="Contenu HTML de l'article", null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True, help_text="Contenu HTML de l'article", null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_fr',
            field=models.TextField(blank=True, help_text="Contenu HTML de l'article", null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/'),
        ),
    ]
