# Generated by Django 5.2.16 on 2026-09-28 04:09

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_site_url_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=core.fields.WebPImageField(blank=True, upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image_1',
            field=core.fields.WebPImageField(blank=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image_2',
            field=core.fields.WebPImageField(blank=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_video_cover',
            field=core.fields.WebPImageField(blank=True, help_text='Image derrière le bouton play. Vide = About image 1.', upload_to='about/video/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_image',
            field=core.fields.WebPImageField(blank=True, upload_to='contact/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image_1',
            field=core.fields.WebPImageField(blank=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image_2',
            field=core.fields.WebPImageField(blank=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image_3',
            field=core.fields.WebPImageField(blank=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_cover',
            field=core.fields.WebPImageField(blank=True, help_text='Image du cadre hero derrière le bouton play. Vide = Hero image 1.', upload_to='hero/video/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=core.fields.WebPImageField(blank=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='why_image_1',
            field=core.fields.WebPImageField(blank=True, upload_to='why/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='why_image_2',
            field=core.fields.WebPImageField(blank=True, upload_to='why/'),
        ),
    ]
