# Generated by Django 5.2.16 on 2026-09-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_partner_logo_alter_sitesettings_about_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Override the default title tag (max 60 chars).', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_card',
            field=models.CharField(blank=True, choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', max_length=20),
        ),
        migrations.AlterField(
            model_name='cookieconsent',
            name='ip_hash',
            field=models.CharField(blank=True, help_text="SHA256 de l'IP client (preuve, aucune IP brute stockée)", max_length=64),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image_1',
            field=models.ImageField(blank=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image_2',
            field=models.ImageField(blank=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_video_cover',
            field=models.ImageField(blank=True, help_text='Image derrière le bouton play. Vide = About image 1.', upload_to='about/video/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_image',
            field=models.ImageField(blank=True, upload_to='contact/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image_1',
            field=models.ImageField(blank=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image_2',
            field=models.ImageField(blank=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image_3',
            field=models.ImageField(blank=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_cover',
            field=models.ImageField(blank=True, help_text='Image du cadre hero derrière le bouton play. Vide = Hero image 1.', upload_to='hero/video/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='why_image_1',
            field=models.ImageField(blank=True, upload_to='why/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='why_image_2',
            field=models.ImageField(blank=True, upload_to='why/'),
        ),
    ]
