# Generated by Django 5.2.16 on 2026-09-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_timelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='image',
            field=models.ImageField(blank=True, upload_to='timeline/'),
        ),
    ]
