# Generated by Django 5.2.16 on 2026-09-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_timelineevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours_weekdays',
            field=models.CharField(blank=True, default='Mon – Fri : 15:00 – 20:00', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours_weekdays_ar',
            field=models.CharField(blank=True, default='Mon – Fri : 15:00 – 20:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours_weekdays_en',
            field=models.CharField(blank=True, default='Mon – Fri : 15:00 – 20:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours_weekdays_fr',
            field=models.CharField(blank=True, default='Mon – Fri : 15:00 – 20:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours_weekend',
            field=models.CharField(blank=True, default='Sat – Sun : 11:00 – 18:00', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours_weekend_ar',
            field=models.CharField(blank=True, default='Sat – Sun : 11:00 – 18:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours_weekend_en',
            field=models.CharField(blank=True, default='Sat – Sun : 11:00 – 18:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours_weekend_fr',
            field=models.CharField(blank=True, default='Sat – Sun : 11:00 – 18:00', max_length=100, null=True),
        ),
    ]
