# Generated by Django 5.2.16 on 2026-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sitesettings_opening_hours_weekdays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('process', 'Services & Process'), ('payments', 'Payments & Budget'), ('warranty', 'Warranty & Support')], default='general', max_length=20),
        ),
    ]
