# Generated by Django 5.2.16 on 2026-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='quote_budget_options',
            field=models.TextField(blank=True, default='Under $50,000\n$50,000 – $150,000\n$150,000 – $500,000\n$500,000 – $1,000,000\n$1,000,000+', help_text='Une option par ligne (budgets du formulaire devis)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quote_budget_options_ar',
            field=models.TextField(blank=True, default='Under $50,000\n$50,000 – $150,000\n$150,000 – $500,000\n$500,000 – $1,000,000\n$1,000,000+', help_text='Une option par ligne (budgets du formulaire devis)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quote_budget_options_en',
            field=models.TextField(blank=True, default='Under $50,000\n$50,000 – $150,000\n$150,000 – $500,000\n$500,000 – $1,000,000\n$1,000,000+', help_text='Une option par ligne (budgets du formulaire devis)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quote_budget_options_fr',
            field=models.TextField(blank=True, default='Under $50,000\n$50,000 – $150,000\n$150,000 – $500,000\n$500,000 – $1,000,000\n$1,000,000+', help_text='Une option par ligne (budgets du formulaire devis)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quote_timeline_options',
            field=models.TextField(blank=True, default="As soon as possible\nWithin 1 – 3 months\nWithin 3 – 6 months\nI'm flexible", help_text='Une option par ligne (délais du formulaire devis)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quote_timeline_options_ar',
            field=models.TextField(blank=True, default="As soon as possible\nWithin 1 – 3 months\nWithin 3 – 6 months\nI'm flexible", help_text='Une option par ligne (délais du formulaire devis)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quote_timeline_options_en',
            field=models.TextField(blank=True, default="As soon as possible\nWithin 1 – 3 months\nWithin 3 – 6 months\nI'm flexible", help_text='Une option par ligne (délais du formulaire devis)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quote_timeline_options_fr',
            field=models.TextField(blank=True, default="As soon as possible\nWithin 1 – 3 months\nWithin 3 – 6 months\nI'm flexible", help_text='Une option par ligne (délais du formulaire devis)', null=True),
        ),
    ]
