# Generated by Django 5.2.16 on 2026-10-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sitesettings_quote_budget_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_image_1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_image_2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_image_3',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_cover',
            field=models.ImageField(blank=True, help_text='Image du cadre hero derrière le bouton play. Vide = Hero image.', upload_to='hero/video/'),
        ),
    ]
