# Generated by Django 5.2.16 on 2026-10-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_hero_single_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_badge_suffix',
            field=models.CharField(blank=True, default='+', help_text='Suffixe du badge (ex : +). Vide = aucun suffixe.', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_badge_value',
            field=models.CharField(blank=True, default='7', help_text="Badge années d'expérience (ex : 7). 7 années révolues depuis le 02/11/2018 ; passer à 8+ à partir de novembre 2026.", max_length=10),
        ),
    ]
