# Generated by Django 5.2.16 on 2026-10-03 16:05

from django.db import migrations


def ensure_singleton(apps, schema_editor):
    # Le singleton est lu en pk=1 partout (save() force pk=1, load()
    # fait get_or_create(pk=1)). Sans ligne, /admin/.../1/change/ => 404.
    SiteSettings = apps.get_model('main', 'SiteSettings')
    if not SiteSettings.objects.filter(pk=1).exists():
        stray = SiteSettings.objects.order_by('pk').first()
        if stray is None:
            SiteSettings.objects.create(pk=1)
        else:
            # Normalise une éventuelle ligne orpheline (pk != 1) vers pk=1.
            SiteSettings.objects.filter(pk=stray.pk).update(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sitesettings_about_badge_suffix_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_singleton, migrations.RunPython.noop),
    ]
